/**
 * Application-layer field encryption — D-035.
 *
 * `submissions.message` is a patient's free-text health complaint. It is stored
 * ONLY as AES-256-GCM authenticated ciphertext; there is no plaintext column,
 * and the key never reaches the database. A database dump on its own is
 * therefore unreadable.
 *
 * 🔴 Operational consequence: a restored backup without the separately-backed-up
 * key map yields permanently unreadable messages. See docs/RUNBOOK-restore.md.
 *
 * Envelope layout — one self-describing `bytea`, so there is no multi-column
 * coordination to get wrong:
 *
 *     byte      0      format version         0x01
 *     byte      1      key-version length     n
 *     bytes  2..1+n    key version (ASCII)    e.g. "v1"
 *     next     12      nonce
 *     next     16      GCM auth tag
 *     remainder        ciphertext
 *
 * The AAD binds a ciphertext to its row and field, so it cannot be moved
 * between rows or columns. That is why `submissions.id` is generated by the
 * application: the id must exist before encryption.
 */

import { createCipheriv, createDecipheriv, randomBytes, randomUUID } from "node:crypto";
import { env, type KeyMap } from "../env";

export const FORMAT_VERSION = 0x01;
export const NONCE_BYTES = 12;
export const TAG_BYTES = 16;
export const KEY_BYTES = 32;
const ALGORITHM = "aes-256-gcm";

/** Plaintext ceiling, matching the schema note and the form's own cap. */
export const MAX_MESSAGE_CHARS = 2000;

export class FieldEncryptionError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "FieldEncryptionError";
  }
}

export class FieldDecryptionError extends Error {
  /** Recorded so the admin UI can name the missing version without guessing. */
  readonly keyVersion: string | undefined;

  constructor(message: string, keyVersion?: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "FieldDecryptionError";
    this.keyVersion = keyVersion;
  }
}

/**
 * Builds the associated data for a field.
 *
 * The trailing `v1` is the AAD *scheme* version, not the key version — it lets
 * the binding format change later without breaking existing rows.
 */
export function aadFor(table: string, id: string, field: string): Buffer {
  return Buffer.from(`${table}|${id}|${field}|v1`, "utf8");
}

export const submissionMessageAad = (submissionId: string): Buffer =>
  aadFor("submissions", submissionId, "message");

/** Application-generated id, required because the AAD binds to it (D-035). */
export const newSubmissionId = (): string => randomUUID();

interface Keyring {
  keys: KeyMap;
  activeVersion: string;
}

function keyring(override?: Keyring): Keyring {
  if (override) return override;
  const e = env();
  return { keys: e.fieldEncryptionKeys, activeVersion: e.fieldEncryptionActiveVersion };
}

/**
 * Encrypts plaintext into the self-describing envelope above.
 *
 * Throws on failure. The caller — `createSubmission` — deliberately catches it
 * and persists the row with `message_encrypted = NULL, message_present = true`,
 * because losing the lead is worse than losing the database copy of a message
 * that already reached the clinic over WhatsApp (D-035 error table).
 */
export function encryptField(
  plaintext: string,
  aad: Buffer,
  override?: Keyring,
): Buffer {
  const { keys, activeVersion } = keyring(override);

  const key = keys.get(activeVersion);
  if (!key) {
    throw new FieldEncryptionError(
      `Active key version "${activeVersion}" is not present in the key map`,
    );
  }

  const versionBytes = Buffer.from(activeVersion, "ascii");
  if (versionBytes.length === 0 || versionBytes.length > 255) {
    throw new FieldEncryptionError(
      `Key version "${activeVersion}" must be 1–255 ASCII bytes`,
    );
  }

  try {
    const nonce = randomBytes(NONCE_BYTES);
    const cipher = createCipheriv(ALGORITHM, key, nonce, { authTagLength: TAG_BYTES });
    cipher.setAAD(aad);

    const ciphertext = Buffer.concat([
      cipher.update(plaintext, "utf8"),
      cipher.final(),
    ]);
    const tag = cipher.getAuthTag();

    return Buffer.concat([
      Buffer.from([FORMAT_VERSION, versionBytes.length]),
      versionBytes,
      nonce,
      tag,
      ciphertext,
    ]);
  } catch (cause) {
    throw new FieldEncryptionError("Encryption failed", { cause });
  }
}

export interface ParsedEnvelope {
  formatVersion: number;
  keyVersion: string;
  nonce: Buffer;
  tag: Buffer;
  ciphertext: Buffer;
}

/** Parses the envelope without needing a key — used by the rotation job. */
export function parseEnvelope(envelope: Buffer): ParsedEnvelope {
  if (envelope.length < 2) {
    throw new FieldDecryptionError("Ciphertext envelope is truncated");
  }

  const formatVersion = envelope[0];
  if (formatVersion !== FORMAT_VERSION) {
    throw new FieldDecryptionError(
      `Unsupported ciphertext format version ${String(formatVersion)}`,
    );
  }

  const versionLength = envelope[1] ?? 0;
  if (versionLength === 0) {
    throw new FieldDecryptionError("Ciphertext envelope has an empty key version");
  }

  const header = 2 + versionLength;
  const minimum = header + NONCE_BYTES + TAG_BYTES;
  if (envelope.length < minimum) {
    throw new FieldDecryptionError("Ciphertext envelope is truncated");
  }

  const keyVersion = envelope.subarray(2, header).toString("ascii");

  return {
    formatVersion,
    keyVersion,
    nonce: envelope.subarray(header, header + NONCE_BYTES),
    tag: envelope.subarray(header + NONCE_BYTES, minimum),
    ciphertext: envelope.subarray(minimum),
  };
}

/**
 * Decrypts an envelope. Fails closed — a tag mismatch throws rather than
 * returning unverified bytes, and a missing key version is reported by name so
 * the detail view can say which key is unavailable instead of rendering a blank
 * field that implies no message was written.
 */
export function decryptField(
  envelope: Buffer,
  aad: Buffer,
  override?: Keyring,
): string {
  const parsed = parseEnvelope(envelope);
  const { keys } = keyring(override);

  const key = keys.get(parsed.keyVersion);
  if (!key) {
    throw new FieldDecryptionError(
      `Key version "${parsed.keyVersion}" is not available`,
      parsed.keyVersion,
    );
  }

  try {
    const decipher = createDecipheriv(ALGORITHM, key, parsed.nonce, {
      authTagLength: TAG_BYTES,
    });
    decipher.setAAD(aad);
    decipher.setAuthTag(parsed.tag);

    return Buffer.concat([
      decipher.update(parsed.ciphertext),
      decipher.final(),
    ]).toString("utf8");
  } catch (cause) {
    // Authentication failure: wrong key, tampered ciphertext, or an AAD that
    // does not match this row. Never echo the ciphertext.
    throw new FieldDecryptionError(
      "Message authentication failed — the ciphertext, key or row binding does not match",
      parsed.keyVersion,
      { cause },
    );
  }
}

/** Convenience wrappers for the one field that is actually encrypted. */
export const encryptSubmissionMessage = (plaintext: string, submissionId: string): Buffer =>
  encryptField(plaintext, submissionMessageAad(submissionId));

export const decryptSubmissionMessage = (envelope: Buffer, submissionId: string): string =>
  decryptField(envelope, submissionMessageAad(submissionId));
